import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Topbar } from "@/components/topbar";
import { ThemeProvider } from "next-themes";
import { ToastProvider } from "@/components/ui/toaster";

const inter = Inter({ variable: "--font-sans", subsets: ["latin"] });
const jetbrains = JetBrains_Mono({ variable: "--font-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" suppressHydrationWarning>
  <body className={`${inter.variable} ${jetbrains.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ToastProvider>
            <Providers>
              <Topbar />
              {children}
            </Providers>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
