import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Topbar } from "@/components/topbar";
import { Sidebar } from "@/components/sidebar";
import { MobileSidebarOverlay } from "@/components/mobile-sidebar-overlay";
import AppShell from "@/components/app-shell";
import { ThemeProvider } from "next-themes";
import { ToastProvider } from "@/components/ui/toaster";

const inter = Inter({ variable: "--font-sans", subsets: ["latin"] });
const jetbrains = JetBrains_Mono({ variable: "--font-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" suppressHydrationWarning>
  <body className={`${inter.variable} ${jetbrains.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false} storageKey="pp-theme-v2">
          <ToastProvider>
            <Providers>
              <a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 focus:z-[100] focus:bg-[var(--pp-panel)] focus:border focus:px-3 focus:py-2 rounded-md">Pomiń do treści</a>
              <AppShell>
                <div className="flex">
                  <Sidebar />
                  <div className="flex-1 min-h-screen md:pl-64">
                    <Topbar />
                    <main id="main-content" className="px-6 py-6">
                      {children}
                    </main>
                  </div>
                </div>
                <MobileSidebarOverlay />
              </AppShell>
            </Providers>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
